version: "3"

services:
  mysql:
    image: mysql:8
    environment:
      -  MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/data:/var/lib/mysql 
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"